// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO
    expenses(
        id,
        item_name,
        category_name,
        quantity,
        unit_cost,
        user_id,
        created_at,
        updated_at
    )
VALUES
    (uuidv7(), $1, $2, $3, $4, $5, NOW(), NOW())
RETURNING
    id, item_name, category_name, quantity, unit_cost, user_id, created_at, updated_at
`

type CreateExpenseParams struct {
	ItemName     string    `json:"item_name"`
	CategoryName string    `json:"category_name"`
	Quantity     int32     `json:"quantity"`
	UnitCost     int32     `json:"unit_cost"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ItemName,
		arg.CategoryName,
		arg.Quantity,
		arg.UnitCost,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ItemName,
		&i.CategoryName,
		&i.Quantity,
		&i.UnitCost,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM
    expenses
WHERE
    id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpenseById = `-- name: GetExpenseById :one
SELECT
    id, item_name, category_name, quantity, unit_cost, user_id, created_at, updated_at
FROM
    expenses
WHERE
    id = $1
`

func (q *Queries) GetExpenseById(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseById, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ItemName,
		&i.CategoryName,
		&i.Quantity,
		&i.UnitCost,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenses = `-- name: GetExpenses :many
SELECT
    id, item_name, category_name, quantity, unit_cost, user_id, created_at, updated_at
FROM
    expenses
`

func (q *Queries) GetExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.ItemName,
			&i.CategoryName,
			&i.Quantity,
			&i.UnitCost,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE
    expenses
SET
    item_name = $1,
    category_name = $2,
    quantity = $3,
    unit_cost = $4,
    updated_at = NOW()
WHERE
    id = $5
RETURNING
    id, item_name, category_name, quantity, unit_cost, user_id, created_at, updated_at
`

type UpdateExpenseParams struct {
	ItemName     string    `json:"item_name"`
	CategoryName string    `json:"category_name"`
	Quantity     int32     `json:"quantity"`
	UnitCost     int32     `json:"unit_cost"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.ItemName,
		arg.CategoryName,
		arg.Quantity,
		arg.UnitCost,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ItemName,
		&i.CategoryName,
		&i.Quantity,
		&i.UnitCost,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
